// Mock actors data with HYBRID identity + INFLUENCE metrics
export const actorsData = [
  {
    id: 'vitalik',
    real_name: 'Vitalik.eth',
    strategy_name: 'L2 Infrastructure Builder',
    identity_confidence: 0.95,
    address: '0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045',
    type: 'Whale',
    avatar: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png',
    confidence: 'high',
    pnl: '+$549K',
    winRate: 66.8,
    riskScore: 12,
    strategies: ['Smart Money', 'DEX Heavy', 'Alpha Hunter'],
    currentBehavior: 'Accumulating',
    behaviorTrend: 'Stable → Bullish',
    tokens: ['ETH', 'L2', 'AI'],
    clusterSize: 4,
    lastAction: { type: 'BUY', token: 'ARB', time: '2h ago', size: '$45K' },
    primaryChain: 'ETH',
    latency: 'Early',
    hasActiveSignals: true,
    signalsCount: 3,
    lastActivityTime: Date.now() - 2 * 60 * 60 * 1000,
    edgeScore: 78,
    influenceScore: 72,
    followers_count: 4,
    leads_count: 1,
    follows_count: 1,
    avgFollowerLag: 5.8,
    consistency: 0.78,
  },
  {
    id: 'alameda',
    real_name: 'Alameda Research',
    strategy_name: 'SOL Ecosystem Accumulator',
    identity_confidence: 0.92,
    address: '0x28C6c06298d514Db089934071355E5743bf21d60',
    type: 'Fund',
    avatar: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/270.png',
    confidence: 'high',
    pnl: '+$2.4M',
    winRate: 71.2,
    riskScore: 8,
    strategies: ['Accumulator', 'Momentum', 'Narrative Rider'],
    currentBehavior: 'Rotating',
    behaviorTrend: 'Active trading',
    tokens: ['SOL', 'BTC', 'DeFi'],
    clusterSize: 12,
    lastAction: { type: 'SWAP', token: 'SOL→USDC', time: '45m ago', size: '$890K' },
    primaryChain: 'SOL',
    latency: 'Early',
    hasActiveSignals: true,
    signalsCount: 5,
    lastActivityTime: Date.now() - 45 * 60 * 1000,
    edgeScore: 86,
    influenceScore: 89,
    followers_count: 6,
    leads_count: 2,
    follows_count: 1,
    avgFollowerLag: 4.5,
    consistency: 0.85,
  },
  {
    id: 'dwf-labs',
    real_name: 'DWF Labs',
    strategy_name: 'Meme Momentum Rider',
    identity_confidence: 0.88,
    address: '0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb',
    type: 'Fund',
    avatar: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/89.png',
    confidence: 'medium',
    pnl: '+$890K',
    winRate: 58.4,
    riskScore: 34,
    strategies: ['Market Maker', 'Early DEX', 'Momentum'],
    currentBehavior: 'Adding',
    behaviorTrend: 'Bullish bias',
    tokens: ['Meme', 'AI', 'Gaming'],
    clusterSize: 8,
    lastAction: { type: 'BUY', token: 'PEPE', time: '4h ago', size: '$120K' },
    primaryChain: 'ETH',
    latency: 'Medium',
    hasActiveSignals: true,
    signalsCount: 2,
    lastActivityTime: Date.now() - 4 * 60 * 60 * 1000,
    edgeScore: 52,
    influenceScore: 38,
    followers_count: 1,
    leads_count: 0,
    follows_count: 3,
    avgFollowerLag: 2.1,
    consistency: 0.52,
  },
  {
    id: 'a16z',
    real_name: 'a16z Crypto',
    strategy_name: 'Institutional Infrastructure Play',
    identity_confidence: 0.97,
    address: '0x47ac0Fb4F2D84898e4D9E7b4DaB3C24507a6D503',
    type: 'Fund',
    avatar: 'https://s2.coinmarketcap.com/static/img/coins/64x64/5426.png',
    confidence: 'high',
    pnl: '+$4.2M',
    winRate: 74.5,
    riskScore: 5,
    strategies: ['Smart Money', 'Long-term', 'Infrastructure'],
    currentBehavior: 'Accumulating',
    behaviorTrend: 'Stable',
    tokens: ['ETH', 'L2', 'Infra'],
    clusterSize: 15,
    lastAction: { type: 'BUY', token: 'OP', time: '1d ago', size: '$2.1M' },
    primaryChain: 'ETH',
    latency: 'Early',
    hasActiveSignals: false,
    signalsCount: 0,
    lastActivityTime: Date.now() - 24 * 60 * 60 * 1000,
    edgeScore: 91,
    influenceScore: 94,
    followers_count: 5,
    leads_count: 3,
    follows_count: 0,
    avgFollowerLag: 6.2,
    consistency: 0.91,
  },
  {
    id: 'jump-trading',
    real_name: 'Jump Trading',
    strategy_name: 'HFT Arbitrage Engine',
    identity_confidence: 0.85,
    address: '0x1234567890abcdef1234567890abcdef12345678',
    type: 'Trader',
    avatar: 'https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png',
    confidence: 'medium',
    pnl: '+$1.1M',
    winRate: 62.3,
    riskScore: 28,
    strategies: ['HFT', 'Arbitrage', 'DEX Heavy'],
    currentBehavior: 'Distributing',
    behaviorTrend: 'Risk-off',
    tokens: ['BTC', 'ETH', 'Stables'],
    clusterSize: 23,
    lastAction: { type: 'SELL', token: 'ETH', time: '30m ago', size: '$340K' },
    primaryChain: 'ETH',
    latency: 'Late',
    hasActiveSignals: true,
    signalsCount: 1,
    lastActivityTime: Date.now() - 30 * 60 * 1000,
    edgeScore: 28,
    influenceScore: 45,
    followers_count: 2,
    leads_count: 2,
    follows_count: 2,
    avgFollowerLag: 1.2,
    consistency: 0.62,
  },
  {
    id: 'unknown-whale-1',
    real_name: 'Smart Whale #4721',
    strategy_name: 'High-Risk Flip Trader',
    identity_confidence: 0.32,
    address: '0xabcdef1234567890abcdef1234567890abcdef12',
    type: 'Whale',
    avatar: null,
    confidence: 'low',
    pnl: '-$124K',
    winRate: 41.2,
    riskScore: 67,
    strategies: ['Momentum', 'Quick Flips'],
    currentBehavior: 'Exiting',
    behaviorTrend: 'Bearish',
    tokens: ['Meme', 'Shitcoins'],
    clusterSize: 2,
    lastAction: { type: 'SELL', token: 'BONK', time: '15m ago', size: '$89K' },
    primaryChain: 'SOL',
    latency: 'Late',
    hasActiveSignals: false,
    signalsCount: 0,
    lastActivityTime: Date.now() - 15 * 60 * 1000,
    edgeScore: 15,
    influenceScore: 18,
    followers_count: 0,
    leads_count: 0,
    follows_count: 4,
    avgFollowerLag: 0,
    consistency: 0.28,
  },
  {
    id: 'pantera',
    real_name: 'Pantera Capital',
    strategy_name: 'AI Narrative Accumulator',
    identity_confidence: 0.94,
    address: '0x9876543210fedcba9876543210fedcba98765432',
    type: 'Fund',
    avatar: 'https://s2.coinmarketcap.com/static/img/coins/64x64/2010.png',
    confidence: 'high',
    pnl: '+$3.8M',
    winRate: 69.1,
    riskScore: 11,
    strategies: ['Smart Money', 'Narrative Rider', 'Early DEX'],
    currentBehavior: 'Accumulating',
    behaviorTrend: 'Bullish',
    tokens: ['AI', 'DeFi', 'L2'],
    clusterSize: 9,
    lastAction: { type: 'BUY', token: 'TAO', time: '6h ago', size: '$1.2M' },
    primaryChain: 'ETH',
    latency: 'Early',
    hasActiveSignals: true,
    signalsCount: 4,
    lastActivityTime: Date.now() - 6 * 60 * 60 * 1000,
    edgeScore: 84,
    influenceScore: 86,
    followers_count: 5,
    leads_count: 2,
    follows_count: 1,
    avgFollowerLag: 4.8,
    consistency: 0.82,
  },
  {
    id: 'wintermute',
    real_name: 'Wintermute',
    strategy_name: 'DeFi Yield Optimizer',
    identity_confidence: 0.87,
    address: '0xfedcba0987654321fedcba0987654321fedcba09',
    type: 'Trader',
    avatar: 'https://s2.coinmarketcap.com/static/img/coins/64x64/4943.png',
    confidence: 'medium',
    pnl: '+$567K',
    winRate: 55.8,
    riskScore: 22,
    strategies: ['Market Maker', 'Arbitrage', 'LP / Yield'],
    currentBehavior: 'Rotating',
    behaviorTrend: 'Neutral',
    tokens: ['ETH', 'Stables', 'DeFi'],
    clusterSize: 31,
    lastAction: { type: 'BRIDGE', token: 'ETH→BASE', time: '1h ago', size: '$780K' },
    primaryChain: 'ETH',
    latency: 'Medium',
    hasActiveSignals: false,
    signalsCount: 0,
    lastActivityTime: Date.now() - 60 * 60 * 1000,
    edgeScore: 45,
    influenceScore: 52,
    followers_count: 1,
    leads_count: 1,
    follows_count: 1,
    avgFollowerLag: 3.2,
    consistency: 0.58,
  },
];
