// ==================== ACTORS DATA ====================
export const actorsData = [
  { id: 'a16z', real_name: 'a16z Crypto', strategy_name: 'Institutional Infrastructure', strategy: 'Infrastructure', edgeScore: 91, followers_count: 5, avg_follower_lag: 6.2, consistency: 0.91, market_impact: 0.85, frontRuns: [{ id: 'alameda', count: 12 }], followedBy: [{ id: 'vitalik', count: 8 }, { id: 'pantera', count: 15 }], correlations: [{ id: 'vitalik', strength: 0.72 }, { id: 'pantera', strength: 0.68 }] },
  { id: 'alameda', real_name: 'Alameda Research', strategy_name: 'SOL Ecosystem Accumulator', strategy: 'Momentum', edgeScore: 86, followers_count: 6, avg_follower_lag: 4.5, consistency: 0.85, market_impact: 0.78, frontRuns: [{ id: 'dwf-labs', count: 24 }], followedBy: [], correlations: [{ id: 'pantera', strength: 0.76 }, { id: 'dwf-labs', strength: 0.52 }] },
  { id: 'pantera', real_name: 'Pantera Capital', strategy_name: 'AI Narrative Accumulator', strategy: 'Smart Money', edgeScore: 84, followers_count: 5, avg_follower_lag: 4.8, consistency: 0.82, market_impact: 0.72, frontRuns: [{ id: 'vitalik', count: 6 }, { id: 'dwf-labs', count: 18 }], followedBy: [], correlations: [{ id: 'a16z', strength: 0.68 }, { id: 'vitalik', strength: 0.71 }] },
  { id: 'vitalik', real_name: 'Vitalik.eth', strategy_name: 'L2 Infrastructure Builder', strategy: 'Smart Money', edgeScore: 78, followers_count: 4, avg_follower_lag: 5.8, consistency: 0.78, market_impact: 0.65, frontRuns: [], followedBy: [{ id: 'pantera', count: 6 }], correlations: [{ id: 'a16z', strength: 0.72 }, { id: 'pantera', strength: 0.71 }] },
  { id: 'wintermute', real_name: 'Wintermute', strategy_name: 'DeFi Yield Optimizer', strategy: 'Market Maker', edgeScore: 45, followers_count: 1, avg_follower_lag: 3.2, consistency: 0.58, market_impact: 0.42, frontRuns: [], followedBy: [], correlations: [{ id: 'jump-trading', strength: 0.64 }] },
  { id: 'jump-trading', real_name: 'Jump Trading', strategy_name: 'HFT Arbitrage Engine', strategy: 'Market Maker', edgeScore: 28, followers_count: 2, avg_follower_lag: 1.2, consistency: 0.62, market_impact: 0.35, frontRuns: [], followedBy: [], correlations: [{ id: 'wintermute', strength: 0.64 }] },
  { id: 'dwf-labs', real_name: 'DWF Labs', strategy_name: 'Meme Momentum Rider', strategy: 'Meme', edgeScore: 52, followers_count: 1, avg_follower_lag: 2.1, consistency: 0.52, market_impact: 0.38, frontRuns: [], followedBy: [{ id: 'alameda', count: 24 }, { id: 'pantera', count: 18 }], correlations: [{ id: 'unknown-whale-1', strength: 0.68 }] },
  { id: 'unknown-whale-1', real_name: 'Smart Whale #4721', strategy_name: 'High-Risk Flip Trader', strategy: 'High Risk', edgeScore: 15, followers_count: 0, avg_follower_lag: 0, consistency: 0.28, market_impact: 0.15, frontRuns: [], followedBy: [{ id: 'vitalik', count: 3 }], correlations: [{ id: 'dwf-labs', strength: 0.68 }] },
];
