// Mock signals data
const createTimestamp = (hoursAgo) => Date.now() - (1000 * 60 * 60 * hoursAgo);

export const mockSignalsData = [
  {
    id: 1,
    address: '0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045',
    label: 'Vitalik Buterin',
    type: 'influencer',
    watchType: 'address',
    verified: true,
    balance: '$45.2M',
    change24h: 5.4,
    txCount: '1,247',
    watching: true,
    behavior: 'accumulating',
    behaviorChanged: false,
    attentionScore: 45,
    deltaSignals: [{ icon: 'spike', text: 'Flow spike vs 7d avg' }],
    statusChange: null,
    riskLevel: 'low',
    bridgeAligned: false,
    dormantDays: 0,
    timestamp: createTimestamp(8),
    muted: false,
    tracking: false
  },
  {
    id: 2,
    address: '0x28C6c06298d514Db089934071355E5743bf21d60',
    label: 'Binance Hot Wallet',
    type: 'exchange',
    watchType: 'cluster',
    verified: true,
    balance: '$2.8B',
    change24h: -2.1,
    txCount: '89,234',
    watching: true,
    behavior: 'distributing',
    behaviorChanged: true,
    attentionScore: 85,
    deltaSignals: [
      { icon: 'change', text: 'Behavior changed 6h ago' },
      { icon: 'aligned', text: 'Aligned with 2 entities' }
    ],
    statusChange: '24h',
    riskLevel: 'high',
    bridgeAligned: true,
    alignedCount: 3,
    alignedEntities: ['Bybit', 'OKX', 'Kraken'],
    coordinationWindow: '6h',
    coordinationConfidence: 87,
    dormantDays: 0,
    timestamp: createTimestamp(1),
    muted: false,
    tracking: false
  },
  {
    id: 3,
    address: '0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb',
    label: 'Unknown Whale',
    type: 'whale',
    watchType: 'address',
    verified: false,
    balance: '$127.5M',
    change24h: 12.8,
    txCount: '456',
    watching: true,
    behavior: 'accumulating',
    behaviorChanged: true,
    attentionScore: 72,
    deltaSignals: [{ icon: 'change', text: 'Behavior changed 3h ago' }],
    statusChange: '24h',
    riskLevel: 'medium',
    bridgeAligned: false,
    dormantDays: 0,
    timestamp: createTimestamp(3),
    muted: false,
    tracking: false
  },
  {
    id: 4,
    address: 'ETH',
    label: 'Ethereum',
    type: 'token',
    watchType: 'token',
    verified: true,
    balance: '$3,342',
    change24h: 2.4,
    txCount: '-',
    watching: true,
    behavior: 'rotating',
    behaviorChanged: false,
    attentionScore: 38,
    deltaSignals: [],
    statusChange: null,
    riskLevel: 'low',
    bridgeAligned: false,
    dormantDays: 0,
    timestamp: createTimestamp(36),
    muted: false,
    tracking: false
  },
  {
    id: 5,
    address: '0x47ac0Fb4F2D84898e4D9E7b4DaB3C24507a6D503',
    label: 'a16z Crypto Fund',
    type: 'fund',
    watchType: 'cluster',
    verified: true,
    balance: '$890.2M',
    change24h: 8.9,
    txCount: '234,567',
    watching: false,
    behavior: 'dormant',
    behaviorChanged: false,
    attentionScore: 12,
    deltaSignals: [],
    statusChange: null,
    riskLevel: 'low',
    bridgeAligned: false,
    dormantDays: 14,
    timestamp: createTimestamp(80),
    muted: false,
    tracking: false
  },
  {
    id: 6,
    address: '0x742d35Cc6634C0532925a3b844Bc9e7595f0bEc',
    label: 'Jump Trading',
    type: 'fund',
    watchType: 'cluster',
    verified: true,
    balance: '$345.8M',
    change24h: -5.2,
    txCount: '12,456',
    watching: true,
    behavior: 'distributing',
    behaviorChanged: false,
    attentionScore: 58,
    deltaSignals: [{ icon: 'aligned', text: 'Aligned with Binance' }],
    statusChange: null,
    riskLevel: 'medium',
    bridgeAligned: true,
    alignedCount: 2,
    alignedEntities: ['Binance', 'Bybit'],
    coordinationWindow: '12h',
    coordinationConfidence: 78,
    dormantDays: 0,
    timestamp: createTimestamp(5),
    muted: false,
    tracking: false
  },
  {
    id: 7,
    address: '0x47ac0Fb4F2D84898e4D9E7b4DaB3C24507a6D507',
    label: 'Coinbase Exchange',
    type: 'exchange',
    verified: true,
    balance: '$1.2B',
    change24h: 1.8,
    txCount: '156,789',
    watching: true,
    behavior: 'rotating',
    behaviorChanged: false,
    attentionScore: 35,
    deltaSignals: [],
    riskLevel: 'low',
    bridgeAligned: false,
    dormantDays: 0,
    timestamp: createTimestamp(12),
    muted: false,
    tracking: false
  },
  {
    id: 8,
    address: '0x8e5c6c06298d514Db089934071355E5743bf21d70',
    label: 'Kraken',
    type: 'exchange',
    verified: true,
    balance: '$890M',
    change24h: -1.2,
    txCount: '98,234',
    watching: true,
    behavior: 'accumulating',
    behaviorChanged: false,
    attentionScore: 42,
    deltaSignals: [],
    riskLevel: 'low',
    bridgeAligned: false,
    dormantDays: 0,
    timestamp: createTimestamp(18),
    muted: false,
    tracking: false
  },
  {
    id: 9,
    address: '0x9e5c6c06298d514Db089934071355E5743bf21d80',
    label: 'Pantera Capital',
    type: 'fund',
    verified: true,
    balance: '$567M',
    change24h: 4.5,
    txCount: '45,678',
    watching: true,
    behavior: 'accumulating',
    behaviorChanged: false,
    attentionScore: 55,
    deltaSignals: [{ icon: 'spike', text: 'Increased activity' }],
    riskLevel: 'medium',
    bridgeAligned: false,
    dormantDays: 0,
    timestamp: createTimestamp(6),
    muted: false,
    tracking: false
  },
  {
    id: 10,
    address: '0xae5c6c06298d514Db089934071355E5743bf21d90',
    label: 'DWF Labs',
    type: 'fund',
    verified: true,
    balance: '$234M',
    change24h: 7.8,
    txCount: '23,456',
    watching: true,
    behavior: 'accumulating',
    behaviorChanged: true,
    attentionScore: 68,
    deltaSignals: [{ icon: 'change', text: 'Behavior changed 12h ago' }],
    statusChange: '24h',
    riskLevel: 'medium',
    bridgeAligned: false,
    dormantDays: 0,
    timestamp: createTimestamp(12),
    muted: false,
    tracking: false
  },
  {
    id: 11,
    address: '0xbe5c6c06298d514Db089934071355E5743bf21da0',
    label: 'Galaxy Digital',
    type: 'fund',
    verified: true,
    balance: '$445M',
    change24h: -3.4,
    txCount: '34,567',
    watching: true,
    behavior: 'distributing',
    behaviorChanged: false,
    attentionScore: 48,
    deltaSignals: [],
    riskLevel: 'medium',
    bridgeAligned: false,
    dormantDays: 0,
    timestamp: createTimestamp(28),
    muted: false,
    tracking: false
  },
  {
    id: 12,
    address: '0xce5c6c06298d514Db089934071355E5743bf21db0',
    label: 'Polychain Capital',
    type: 'fund',
    verified: true,
    balance: '$312M',
    change24h: 2.1,
    txCount: '28,901',
    watching: true,
    behavior: 'accumulating',
    behaviorChanged: false,
    attentionScore: 41,
    deltaSignals: [],
    riskLevel: 'low',
    bridgeAligned: false,
    dormantDays: 0,
    timestamp: createTimestamp(40),
    muted: false,
    tracking: false
  },
  {
    id: 13,
    address: '0xde5c6c06298d514Db089934071355E5743bf21dc0',
    label: 'Three Arrows Capital',
    type: 'fund',
    verified: true,
    balance: '$0',
    change24h: 0,
    txCount: '1,234',
    watching: true,
    behavior: 'dormant',
    behaviorChanged: false,
    attentionScore: 5,
    deltaSignals: [],
    riskLevel: 'low',
    bridgeAligned: false,
    dormantDays: 365,
    timestamp: createTimestamp(100),
    muted: false,
    tracking: false
  }
];
